Add serversTransports for self-signed certificate verification
NethServer/ns8-traefik pull request #49
Opened 2024-01-09 11:53 UTC by stephdl

This pull request adds the `serversTransports` configuration to support self-signed certificate verification. It also adds the `skipCertVerify` flag to the `get_route` function for handling custom certificates.

2024-01-10 15:34 UTC, Amygos requested changes

2024-01-10 15:34 UTC, Amygos commented on imageroot/actions/list-routes/validate-output.json
> -	    []
The empty array is still a valid output

2024-01-10 15:34 UTC, Amygos commented on imageroot/actions/get-route/validate-output.json
> +        "skipCertVerify": {
```suggestion
        "skip_cert_verify": {
```
I prefer the use of the snake case instead of the camel case, to remain consistent with the style of the other fields.

2024-01-10 15:34 UTC, Amygos commented on imageroot/actions/list-routes/validate-output.json
> +    "title": "list-routes output",
Why did you move this line?

2024-01-10 17:53 UTC, stephdl commented on imageroot/actions/list-routes/validate-output.json
> -	    []
done

2024-01-10 17:53 UTC, stephdl commented on imageroot/actions/list-routes/validate-output.json
> +    "title": "list-routes output",
done

2024-01-10 17:55 UTC, stephdl commented on imageroot/actions/get-route/validate-output.json
> +        "skipCertVerify": {
done

2024-01-11 08:58 UTC, Amygos approved these changes

2024-01-11 11:39 UTC, merged