Improve Custom Certificate Handling and Redis Storage
NethServer/ns8-traefik pull request #62
Opened 2024-09-04 13:53 UTC by Amygos

This pull request enhances the management of custom certificates, including improvements to Redis storage and certificate handling logic.

**Key Changes:**
- **Delete Certificate:**
  - Improved logic to ensure custom certificates are correctly removed from Redis when requested FQDN is deleted.
  - Prevent unnecessary attempts to remove internal certificates when dealing with custom ones.

- **Export Certificate:**
  - Added safeguard to avoid overriding custom certificates during the export process.

- **Upload Certificate:**
  - Implemented logic to store custom certificates directly in Redis.

- **Testing:**
  - Added and updated tests to verify that custom certificates are correctly handled and stored in Redis.

2024-09-04 14:05 UTC, Tbaile requested changes

2024-09-04 14:05 UTC, Tbaile commented on imageroot/actions/upload-certificate/23export_certificates
> +    domain = subject.split("\n")[1].split("CN=")[1]
It's possible that there's no common name in the certificate as far as `X.509` specification goes, I'd suggest a fallback option

2024-09-04 14:05 UTC, Tbaile commented on imageroot/actions/upload-certificate/23export_certificates
> +with subprocess.Popen(['openssl', 'x509', '-noout', '-subject', '-in', '/dev/stdin', '-nameopt', 'sep_multiline', '-nameopt', 'utf8'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True) as ope
`Popen` is the overkill underlying constructor for `subprocess.run`, I'd suggest sticking to that (with `capture_output` and `text`)

2024-09-04 14:10 UTC, Amygos commented on imageroot/actions/upload-certificate/23export_certificates
> +    domain = subject.split("\n")[1].split("CN=")[1]
A certificate without a common name passes the validation of  [21validate_certificates ](https://github.com/NethServer/ns8-traefik/blob/51c20c8a6f28330bb8025b3d802a445855d00ce3/imageroot/actions/upload-certificate/21validate_certificates)?

2024-09-04 14:12 UTC, Amygos commented on imageroot/actions/upload-certificate/23export_certificates
> +    domain = subject.split("\n")[1].split("CN=")[1]
All the validation steps are made [21validate_certificates ](https://github.com/NethServer/ns8-traefik/blob/51c20c8a6f28330bb8025b3d802a445855d00ce3/imageroot/actions/upload-certificate/21validate_certificates)?

2024-09-04 14:12 UTC, Tbaile commented on imageroot/actions/upload-certificate/23export_certificates
> +    domain = subject.split("\n")[1].split("CN=")[1]
Yes, sadly, not because the validation is faulty, [but because the specification says so](https://security.stackexchange.com/questions/55414/is-the-common-name-mandatory-for-digital-certificates) :shrug:

2024-09-04 14:16 UTC, Amygos commented on imageroot/actions/upload-certificate/23export_certificates
> +    domain = subject.split("\n")[1].split("CN=")[1]
so there is the same problem [here](https://github.com/NethServer/ns8-traefik/blob/51c20c8a6f28330bb8025b3d802a445855d00ce3/imageroot/actions/upload-certificate/22save_certificates#L17), right?

2024-09-04 14:20 UTC, Tbaile commented on imageroot/actions/upload-certificate/23export_certificates
> +    domain = subject.split("\n")[1].split("CN=")[1]
It appears so, learned of this caveat myself when wrote the Nethsecurity certificates handler api

2024-09-04 14:28 UTC, Amygos commented on imageroot/actions/upload-certificate/23export_certificates
> +    domain = subject.split("\n")[1].split("CN=")[1]
As suggested by the above answer on StackExchange, I think we can request as mandatory the presence of the common name, what do you think @DavidePrincipi ?
> However, a number of systems will use the CN for display purposes, e.g. most "certificate manager" GUI in Windows. Therefore, it is recommended, if only for ease of sysadmin tasks, to include reasonably precise CN in certificates.

@Tbaile how do you have handled the case on Nethsecurity?

2024-09-04 14:33 UTC, gsanchietti commented on imageroot/actions/upload-certificate/23export_certificates
> +    domain = subject.split("\n")[1].split("CN=")[1]
I guess most of purchased certificates do have a valid common name.
I'd move the check on the validation step.

2024-09-04 15:15 UTC, Amygos commented on imageroot/actions/upload-certificate/23export_certificates
> +    domain = subject.split("\n")[1].split("CN=")[1]
Ok, I will also implement the validation in case of empty `CN` filed.

2024-09-05 06:39 UTC, gsanchietti approved these changes

2024-09-05 06:40 UTC, Tbaile commented on imageroot/actions/upload-certificate/21validate_certificates
> +    del_certs
Maybe there's the need for the agent to send a validation error?
```suggestion
    del_certs
    agent.set_status('validation-failed')
```

I'll leave the judgment to @andre8244 :pray:

2024-09-05 07:28 UTC, stephdl approved these changes

2024-09-05 08:24 UTC, andre8244 commented on imageroot/actions/upload-certificate/21validate_certificates
> +    del_certs
It would be nice to have a validation error, but this would need a little adjustment on the UI too. I guess it's worth it only if the chance of this error to occur is not too rare.

2024-09-05 08:27 UTC, Amygos commented on imageroot/actions/upload-certificate/21validate_certificates
> +    del_certs
You are right, it is better to signal a validation error in this case properly, but there are two major problems here:
* the file is a shell script, not a python script
* the changes are too out of scope for this PR

But I am happy to address this issue in another PR :)

2024-09-05 09:49 UTC, Tbaile commented on imageroot/actions/upload-certificate/21validate_certificates
> +    del_certs
Then all good :partying_face:

2024-09-05 09:49 UTC, Tbaile approved these changes

2024-09-05 09:55 UTC, Amygos commented on imageroot/actions/upload-certificate/21validate_certificates
> +    echo "Certificate doesn't have a common name."
Ok, I will make the related corrections in another PR.

2024-09-05 09:56 UTC, merged

2024-09-05 12:51 UTC, Amygos commented on imageroot/actions/upload-certificate/21validate_certificates
> +    echo "Certificate doesn't have a common name."
Fix in https://github.com/NethServer/ns8-traefik/pull/63